[package]
name = "nexusproxy-policy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nexusproxy-parser = { path = "../parser" }
tokio = { workspace = true, features = ["sync"] }
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
thiserror.workspace = true
chrono.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
